---
title: "Loading_Speed_VR"
author: "Brian Wright"
date: "January 17, 2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(feather)
getwd()
```


```{r eruptions, echo=FALSE}
#so you would likely include coding here to convert the file to feather then in the render block call the feather object, another example:


#VR_data <- fread("VR_Data2.csv")#Read in the data one time with Fread

path_vr_feather <- ("VR_Data2.feather")#Create the path to write the Feather file

write_feather(VR_data,path_vr_feather)#Writes the feather file, then we would call the data in the app itself.

vr_data2 <- read_feather("VR_Data2.feather")
```

```{r eruptions, echo=FALSE}

inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 30, 50, 70), selected = 30),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  vr_data2 <- read_feather("VR_Data2.feather")
  hist(vr_data2$hr, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Average HR (Seconds)", main = "Average Heart Rate Per Minute")
  
  dens <- density(vr_data2$hr, adjust = input$bw_adjust)
  lines(dens, col = "red")
})


```



